import { defineStore } from "pinia";

export const calendarStore = defineStore("calendar", {
  state: () => ({
    _locale: "pt-BR",
    _allowedColors: [
      "blue",
      "indigo",
      "green",
      "cyan",
      "red",
      "pink",
      "purple",
      "yellow",
      "orange",
      "brown",
      "grey",
      "dark",
    ],
    _allowedIcons: [
      "favorite",
      "auto_stories",
      "grade",
      "flight_takeoff",
      "fitness_center",
      "textsms",
      "work",
      "bookmark",
      "warning",
      "light_mode",
      "celebration",
      "cake",
      "pets",
      "style",
      "savings",
      "room",
      "pending",
      "record_voice_over",
      "sports_esports",
      "restaurant",
      "diversity_1",
      "fastfood",
      "airport_shuttle",
      "sports_bar",
    ],
    _events: [
      {
        id: 1,
        title: "Estudar VueJS",
        details: "Hora de aprender!",
        date: "2023-04-01",
        time: null,
        duration: null,
        bgcolor: "orange",
        icon: "auto_stories",
      },
      {
        id: 2,
        title: "Aniversário de Fulano",
        details: "Comprar um presente bem legal",
        date: "2023-04-04",
        time: null,
        duration: null,
        bgcolor: "green",
        icon: "cake",
      },
      {
        id: 3,
        title: "Meeting",
        details: "Hora de conversar com o time da empresa",
        date: "2023-04-10",
        time: "10:00",
        duration: 120,
        bgcolor: "red",
        icon: "textsms",
      },
      {
        id: 4,
        title: "Almoço",
        details: "A melhor hora do dia!",
        date: "2023-04-10",
        time: "11:30",
        duration: 90,
        bgcolor: "indigo",
      },
      {
        id: 5,
        title: "Visitar a mãe",
        details: "Levar flores",
        date: "2023-04-20",
        time: "17:00",
        duration: 90,
        bgcolor: "grey",
        icon: "favorite",
      },
      {
        id: 6,
        title: "Conferência",
        details: "Vamos pro CCXP",
        date: "2023-04-22",
        time: "08:00",
        duration: 540,
        bgcolor: "blue",
      },
      {
        id: 7,
        title: "Encontro com o cliente",
        details: "Reservar um bom restaurante",
        date: "2023-04-22",
        time: "19:00",
        duration: 180,
        bgcolor: "orange",
      },
      {
        id: 8,
        title: "Estudar Ruby on Rais",
        details: "Hora de aprender!",
        date: "2023-04-27",
        time: null,
        duration: null,
        bgcolor: "purple",
        icon: "auto_stories",
        days: 2,
      },
      {
        id: 9,
        title: "Pescaria",
        details: "Não esquecer o anzol",
        date: "2023-04-27",
        time: null,
        duration: null,
        bgcolor: "pink",
        days: 2,
      },
      {
        id: 10,
        title: "Férias",
        details: "Vamos para Florianópolis!",
        date: "2023-04-29",
        time: null,
        duration: null,
        bgcolor: "purple",
        icon: "flight_takeoff",
        days: 5,
      },
    ],
  }),
  getters: {
    getLocale: (state) => state._locale,
    getAllowedColors: (state) => state._allowedColors,
    getAllowedIcons: (state) => state._allowedIcons,
    getEvents: (state) => state._events,
  },
  actions: {
    async addEvent(event) {
      console.log(event);
      // removendo chaves nulas do objeto por causa do bug do QCalendar
      for (const [key, value] of Object.entries(event))
        if (value === null) delete event[key];
      this._events.push(event);
    },
  },
});
